/********************************************************************************
** Form generated from reading UI file 'acm.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ACM_H
#define UI_ACM_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTableWidget>

QT_BEGIN_NAMESPACE

class Ui_ACM
{
public:
    QLabel *label;
    QLabel *label_2;
    QLabel *cname_label;
    QLabel *aname_label;
    QLabel *txt_clientname;
    QLabel *txt_animalname;
    QLabel *PAtitle_label;
    QLabel *cspecies_label;
    QLabel *aspecies_label;
    QLabel *txt_cspecies;
    QLabel *txt_aspecies;
    QLabel *cbreed_label;
    QLabel *abreed_label;
    QLabel *csex_label;
    QLabel *asex_label;
    QLabel *txt_cbreed;
    QLabel *txt_abreed;
    QLabel *txt_csex;
    QLabel *txt_asex;
    QLabel *cage_label;
    QLabel *aage_label;
    QLabel *txt_cage;
    QLabel *txt_aage;
    QLabel *NPAtitle_label;
    QLabel *NPA1_label;
    QLabel *NPA1_label_2;
    QLabel *txt_NPA1;
    QLabel *txt_NPA1_2;
    QLabel *NPA2_label;
    QLabel *NPA2_label_2;
    QLabel *NPA3_label;
    QLabel *NPA3_label_2;
    QLabel *NPA4_label;
    QLabel *NPA4_label_2;
    QLabel *NPA5_label;
    QLabel *NPA5_label_2;
    QLabel *NPA6_label;
    QLabel *NPA6_label_2;
    QLabel *NPA7_label;
    QLabel *NPA7_label_2;
    QLabel *NPA8_label;
    QLabel *NPA8_label_2;
    QLabel *NPA9_label;
    QLabel *NPA9_label_2;
    QLabel *NPA10_label;
    QLabel *NPA10_label_2;
    QLabel *NPA11_label;
    QLabel *NPA11_label_2;
    QLabel *NPA12_label;
    QLabel *NPA12_label_2;
    QLabel *txt_NPA2;
    QLabel *txt_NPA2_2;
    QLabel *txt_NPA3;
    QLabel *txt_NPA3_2;
    QLabel *txt_NPA4;
    QLabel *txt_NPA4_2;
    QLabel *txt_NPA5;
    QLabel *txt_NPA5_2;
    QLabel *txt_NPA6;
    QLabel *txt_NPA6_2;
    QLabel *txt_NPA7;
    QLabel *txt_NPA7_2;
    QLabel *txt_NPA8;
    QLabel *txt_NPA8_2;
    QLabel *txt_NPA9;
    QLabel *txt_NPA9_2;
    QLabel *txt_NPA10;
    QLabel *txt_NPA10_2;
    QLabel *txt_NPA11;
    QLabel *txt_NPA11_2;
    QLabel *txt_NPA12;
    QLabel *txt_NPA12_2;
    QPushButton *backButton;
    QLabel *ACMTitle;
    QTableWidget *ACMResultsTable;

    void setupUi(QDialog *ACM)
    {
        if (ACM->objectName().isEmpty())
            ACM->setObjectName(QStringLiteral("ACM"));
        ACM->resize(953, 619);
        label = new QLabel(ACM);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(520, 10, 64, 17));
        QFont font;
        font.setFamily(QStringLiteral("DejaVu Sans"));
        font.setPointSize(12);
        font.setBold(true);
        font.setItalic(true);
        font.setWeight(75);
        label->setFont(font);
        label_2 = new QLabel(ACM);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(800, 10, 64, 17));
        label_2->setFont(font);
        cname_label = new QLabel(ACM);
        cname_label->setObjectName(QStringLiteral("cname_label"));
        cname_label->setGeometry(QRect(470, 40, 64, 17));
        aname_label = new QLabel(ACM);
        aname_label->setObjectName(QStringLiteral("aname_label"));
        aname_label->setGeometry(QRect(700, 40, 64, 17));
        txt_clientname = new QLabel(ACM);
        txt_clientname->setObjectName(QStringLiteral("txt_clientname"));
        txt_clientname->setGeometry(QRect(530, 40, 150, 20));
        txt_clientname->setMinimumSize(QSize(150, 20));
        txt_clientname->setMaximumSize(QSize(150, 20));
        txt_animalname = new QLabel(ACM);
        txt_animalname->setObjectName(QStringLiteral("txt_animalname"));
        txt_animalname->setGeometry(QRect(760, 40, 150, 20));
        txt_animalname->setMinimumSize(QSize(150, 20));
        txt_animalname->setMaximumSize(QSize(150, 20));
        PAtitle_label = new QLabel(ACM);
        PAtitle_label->setObjectName(QStringLiteral("PAtitle_label"));
        PAtitle_label->setGeometry(QRect(640, 70, 141, 16));
        QFont font1;
        font1.setFamily(QStringLiteral("DejaVu Sans"));
        font1.setBold(true);
        font1.setItalic(true);
        font1.setWeight(75);
        PAtitle_label->setFont(font1);
        cspecies_label = new QLabel(ACM);
        cspecies_label->setObjectName(QStringLiteral("cspecies_label"));
        cspecies_label->setGeometry(QRect(470, 100, 64, 17));
        aspecies_label = new QLabel(ACM);
        aspecies_label->setObjectName(QStringLiteral("aspecies_label"));
        aspecies_label->setGeometry(QRect(700, 100, 64, 17));
        txt_cspecies = new QLabel(ACM);
        txt_cspecies->setObjectName(QStringLiteral("txt_cspecies"));
        txt_cspecies->setGeometry(QRect(530, 100, 150, 20));
        txt_cspecies->setMinimumSize(QSize(150, 20));
        txt_cspecies->setMaximumSize(QSize(150, 20));
        txt_aspecies = new QLabel(ACM);
        txt_aspecies->setObjectName(QStringLiteral("txt_aspecies"));
        txt_aspecies->setGeometry(QRect(760, 100, 150, 20));
        txt_aspecies->setMinimumSize(QSize(150, 20));
        txt_aspecies->setMaximumSize(QSize(150, 20));
        cbreed_label = new QLabel(ACM);
        cbreed_label->setObjectName(QStringLiteral("cbreed_label"));
        cbreed_label->setGeometry(QRect(470, 130, 64, 17));
        abreed_label = new QLabel(ACM);
        abreed_label->setObjectName(QStringLiteral("abreed_label"));
        abreed_label->setGeometry(QRect(700, 130, 64, 17));
        csex_label = new QLabel(ACM);
        csex_label->setObjectName(QStringLiteral("csex_label"));
        csex_label->setGeometry(QRect(470, 160, 64, 17));
        asex_label = new QLabel(ACM);
        asex_label->setObjectName(QStringLiteral("asex_label"));
        asex_label->setGeometry(QRect(700, 160, 64, 17));
        txt_cbreed = new QLabel(ACM);
        txt_cbreed->setObjectName(QStringLiteral("txt_cbreed"));
        txt_cbreed->setGeometry(QRect(530, 130, 150, 20));
        txt_cbreed->setMinimumSize(QSize(150, 20));
        txt_cbreed->setMaximumSize(QSize(150, 20));
        txt_abreed = new QLabel(ACM);
        txt_abreed->setObjectName(QStringLiteral("txt_abreed"));
        txt_abreed->setGeometry(QRect(760, 130, 150, 20));
        txt_abreed->setMinimumSize(QSize(150, 20));
        txt_abreed->setMaximumSize(QSize(150, 20));
        txt_csex = new QLabel(ACM);
        txt_csex->setObjectName(QStringLiteral("txt_csex"));
        txt_csex->setGeometry(QRect(530, 160, 150, 20));
        txt_csex->setMinimumSize(QSize(150, 20));
        txt_csex->setMaximumSize(QSize(150, 20));
        txt_asex = new QLabel(ACM);
        txt_asex->setObjectName(QStringLiteral("txt_asex"));
        txt_asex->setGeometry(QRect(760, 160, 150, 20));
        txt_asex->setMinimumSize(QSize(150, 20));
        txt_asex->setMaximumSize(QSize(150, 20));
        cage_label = new QLabel(ACM);
        cage_label->setObjectName(QStringLiteral("cage_label"));
        cage_label->setGeometry(QRect(470, 190, 64, 17));
        aage_label = new QLabel(ACM);
        aage_label->setObjectName(QStringLiteral("aage_label"));
        aage_label->setGeometry(QRect(700, 190, 64, 17));
        txt_cage = new QLabel(ACM);
        txt_cage->setObjectName(QStringLiteral("txt_cage"));
        txt_cage->setGeometry(QRect(530, 190, 150, 20));
        txt_cage->setMinimumSize(QSize(150, 20));
        txt_cage->setMaximumSize(QSize(150, 20));
        txt_aage = new QLabel(ACM);
        txt_aage->setObjectName(QStringLiteral("txt_aage"));
        txt_aage->setGeometry(QRect(760, 190, 150, 20));
        txt_aage->setMinimumSize(QSize(150, 20));
        txt_aage->setMaximumSize(QSize(150, 20));
        NPAtitle_label = new QLabel(ACM);
        NPAtitle_label->setObjectName(QStringLiteral("NPAtitle_label"));
        NPAtitle_label->setGeometry(QRect(620, 230, 191, 16));
        NPAtitle_label->setFont(font1);
        NPA1_label = new QLabel(ACM);
        NPA1_label->setObjectName(QStringLiteral("NPA1_label"));
        NPA1_label->setGeometry(QRect(470, 260, 41, 17));
        NPA1_label_2 = new QLabel(ACM);
        NPA1_label_2->setObjectName(QStringLiteral("NPA1_label_2"));
        NPA1_label_2->setGeometry(QRect(700, 260, 41, 17));
        txt_NPA1 = new QLabel(ACM);
        txt_NPA1->setObjectName(QStringLiteral("txt_NPA1"));
        txt_NPA1->setGeometry(QRect(530, 260, 150, 20));
        txt_NPA1->setMinimumSize(QSize(150, 20));
        txt_NPA1->setMaximumSize(QSize(150, 20));
        txt_NPA1_2 = new QLabel(ACM);
        txt_NPA1_2->setObjectName(QStringLiteral("txt_NPA1_2"));
        txt_NPA1_2->setGeometry(QRect(760, 260, 150, 20));
        txt_NPA1_2->setMinimumSize(QSize(150, 20));
        txt_NPA1_2->setMaximumSize(QSize(150, 20));
        NPA2_label = new QLabel(ACM);
        NPA2_label->setObjectName(QStringLiteral("NPA2_label"));
        NPA2_label->setGeometry(QRect(470, 290, 41, 17));
        NPA2_label_2 = new QLabel(ACM);
        NPA2_label_2->setObjectName(QStringLiteral("NPA2_label_2"));
        NPA2_label_2->setGeometry(QRect(700, 290, 41, 17));
        NPA3_label = new QLabel(ACM);
        NPA3_label->setObjectName(QStringLiteral("NPA3_label"));
        NPA3_label->setGeometry(QRect(470, 320, 41, 17));
        NPA3_label_2 = new QLabel(ACM);
        NPA3_label_2->setObjectName(QStringLiteral("NPA3_label_2"));
        NPA3_label_2->setGeometry(QRect(700, 320, 41, 17));
        NPA4_label = new QLabel(ACM);
        NPA4_label->setObjectName(QStringLiteral("NPA4_label"));
        NPA4_label->setGeometry(QRect(470, 350, 41, 17));
        NPA4_label_2 = new QLabel(ACM);
        NPA4_label_2->setObjectName(QStringLiteral("NPA4_label_2"));
        NPA4_label_2->setGeometry(QRect(700, 350, 41, 17));
        NPA5_label = new QLabel(ACM);
        NPA5_label->setObjectName(QStringLiteral("NPA5_label"));
        NPA5_label->setGeometry(QRect(470, 380, 41, 17));
        NPA5_label_2 = new QLabel(ACM);
        NPA5_label_2->setObjectName(QStringLiteral("NPA5_label_2"));
        NPA5_label_2->setGeometry(QRect(700, 380, 41, 17));
        NPA6_label = new QLabel(ACM);
        NPA6_label->setObjectName(QStringLiteral("NPA6_label"));
        NPA6_label->setGeometry(QRect(470, 410, 41, 17));
        NPA6_label_2 = new QLabel(ACM);
        NPA6_label_2->setObjectName(QStringLiteral("NPA6_label_2"));
        NPA6_label_2->setGeometry(QRect(700, 410, 41, 17));
        NPA7_label = new QLabel(ACM);
        NPA7_label->setObjectName(QStringLiteral("NPA7_label"));
        NPA7_label->setGeometry(QRect(470, 440, 41, 17));
        NPA7_label_2 = new QLabel(ACM);
        NPA7_label_2->setObjectName(QStringLiteral("NPA7_label_2"));
        NPA7_label_2->setGeometry(QRect(700, 440, 41, 17));
        NPA8_label = new QLabel(ACM);
        NPA8_label->setObjectName(QStringLiteral("NPA8_label"));
        NPA8_label->setGeometry(QRect(470, 470, 41, 17));
        NPA8_label_2 = new QLabel(ACM);
        NPA8_label_2->setObjectName(QStringLiteral("NPA8_label_2"));
        NPA8_label_2->setGeometry(QRect(700, 470, 41, 17));
        NPA9_label = new QLabel(ACM);
        NPA9_label->setObjectName(QStringLiteral("NPA9_label"));
        NPA9_label->setGeometry(QRect(470, 500, 41, 17));
        NPA9_label_2 = new QLabel(ACM);
        NPA9_label_2->setObjectName(QStringLiteral("NPA9_label_2"));
        NPA9_label_2->setGeometry(QRect(700, 500, 41, 17));
        NPA10_label = new QLabel(ACM);
        NPA10_label->setObjectName(QStringLiteral("NPA10_label"));
        NPA10_label->setGeometry(QRect(470, 530, 51, 17));
        NPA10_label_2 = new QLabel(ACM);
        NPA10_label_2->setObjectName(QStringLiteral("NPA10_label_2"));
        NPA10_label_2->setGeometry(QRect(700, 530, 51, 17));
        NPA11_label = new QLabel(ACM);
        NPA11_label->setObjectName(QStringLiteral("NPA11_label"));
        NPA11_label->setGeometry(QRect(470, 560, 51, 17));
        NPA11_label_2 = new QLabel(ACM);
        NPA11_label_2->setObjectName(QStringLiteral("NPA11_label_2"));
        NPA11_label_2->setGeometry(QRect(700, 560, 51, 17));
        NPA12_label = new QLabel(ACM);
        NPA12_label->setObjectName(QStringLiteral("NPA12_label"));
        NPA12_label->setGeometry(QRect(470, 590, 51, 17));
        NPA12_label_2 = new QLabel(ACM);
        NPA12_label_2->setObjectName(QStringLiteral("NPA12_label_2"));
        NPA12_label_2->setGeometry(QRect(700, 590, 51, 17));
        txt_NPA2 = new QLabel(ACM);
        txt_NPA2->setObjectName(QStringLiteral("txt_NPA2"));
        txt_NPA2->setGeometry(QRect(530, 290, 150, 20));
        txt_NPA2->setMinimumSize(QSize(150, 20));
        txt_NPA2->setMaximumSize(QSize(150, 20));
        txt_NPA2_2 = new QLabel(ACM);
        txt_NPA2_2->setObjectName(QStringLiteral("txt_NPA2_2"));
        txt_NPA2_2->setGeometry(QRect(760, 290, 150, 20));
        txt_NPA2_2->setMinimumSize(QSize(150, 20));
        txt_NPA2_2->setMaximumSize(QSize(150, 20));
        txt_NPA3 = new QLabel(ACM);
        txt_NPA3->setObjectName(QStringLiteral("txt_NPA3"));
        txt_NPA3->setGeometry(QRect(530, 320, 150, 20));
        txt_NPA3->setMinimumSize(QSize(150, 20));
        txt_NPA3->setMaximumSize(QSize(150, 20));
        txt_NPA3_2 = new QLabel(ACM);
        txt_NPA3_2->setObjectName(QStringLiteral("txt_NPA3_2"));
        txt_NPA3_2->setGeometry(QRect(760, 320, 150, 20));
        txt_NPA3_2->setMinimumSize(QSize(150, 20));
        txt_NPA3_2->setMaximumSize(QSize(150, 20));
        txt_NPA4 = new QLabel(ACM);
        txt_NPA4->setObjectName(QStringLiteral("txt_NPA4"));
        txt_NPA4->setGeometry(QRect(530, 350, 150, 20));
        txt_NPA4->setMinimumSize(QSize(150, 20));
        txt_NPA4->setMaximumSize(QSize(150, 20));
        txt_NPA4_2 = new QLabel(ACM);
        txt_NPA4_2->setObjectName(QStringLiteral("txt_NPA4_2"));
        txt_NPA4_2->setGeometry(QRect(760, 350, 150, 20));
        txt_NPA4_2->setMinimumSize(QSize(150, 20));
        txt_NPA4_2->setMaximumSize(QSize(150, 20));
        txt_NPA5 = new QLabel(ACM);
        txt_NPA5->setObjectName(QStringLiteral("txt_NPA5"));
        txt_NPA5->setGeometry(QRect(530, 380, 150, 20));
        txt_NPA5->setMinimumSize(QSize(150, 20));
        txt_NPA5->setMaximumSize(QSize(150, 20));
        txt_NPA5_2 = new QLabel(ACM);
        txt_NPA5_2->setObjectName(QStringLiteral("txt_NPA5_2"));
        txt_NPA5_2->setGeometry(QRect(760, 380, 150, 20));
        txt_NPA5_2->setMinimumSize(QSize(150, 20));
        txt_NPA5_2->setMaximumSize(QSize(150, 20));
        txt_NPA6 = new QLabel(ACM);
        txt_NPA6->setObjectName(QStringLiteral("txt_NPA6"));
        txt_NPA6->setGeometry(QRect(530, 410, 150, 20));
        txt_NPA6->setMinimumSize(QSize(150, 20));
        txt_NPA6->setMaximumSize(QSize(150, 20));
        txt_NPA6_2 = new QLabel(ACM);
        txt_NPA6_2->setObjectName(QStringLiteral("txt_NPA6_2"));
        txt_NPA6_2->setGeometry(QRect(760, 410, 150, 20));
        txt_NPA6_2->setMinimumSize(QSize(150, 20));
        txt_NPA6_2->setMaximumSize(QSize(150, 20));
        txt_NPA7 = new QLabel(ACM);
        txt_NPA7->setObjectName(QStringLiteral("txt_NPA7"));
        txt_NPA7->setGeometry(QRect(530, 440, 150, 20));
        txt_NPA7->setMinimumSize(QSize(150, 20));
        txt_NPA7->setMaximumSize(QSize(150, 20));
        txt_NPA7_2 = new QLabel(ACM);
        txt_NPA7_2->setObjectName(QStringLiteral("txt_NPA7_2"));
        txt_NPA7_2->setGeometry(QRect(760, 440, 150, 20));
        txt_NPA7_2->setMinimumSize(QSize(150, 20));
        txt_NPA7_2->setMaximumSize(QSize(150, 20));
        txt_NPA8 = new QLabel(ACM);
        txt_NPA8->setObjectName(QStringLiteral("txt_NPA8"));
        txt_NPA8->setGeometry(QRect(530, 470, 150, 20));
        txt_NPA8->setMinimumSize(QSize(150, 20));
        txt_NPA8->setMaximumSize(QSize(150, 20));
        txt_NPA8_2 = new QLabel(ACM);
        txt_NPA8_2->setObjectName(QStringLiteral("txt_NPA8_2"));
        txt_NPA8_2->setGeometry(QRect(760, 470, 150, 20));
        txt_NPA8_2->setMinimumSize(QSize(150, 20));
        txt_NPA8_2->setMaximumSize(QSize(150, 20));
        txt_NPA9 = new QLabel(ACM);
        txt_NPA9->setObjectName(QStringLiteral("txt_NPA9"));
        txt_NPA9->setGeometry(QRect(530, 500, 150, 20));
        txt_NPA9->setMinimumSize(QSize(150, 20));
        txt_NPA9->setMaximumSize(QSize(150, 20));
        txt_NPA9_2 = new QLabel(ACM);
        txt_NPA9_2->setObjectName(QStringLiteral("txt_NPA9_2"));
        txt_NPA9_2->setGeometry(QRect(760, 500, 150, 20));
        txt_NPA9_2->setMinimumSize(QSize(150, 20));
        txt_NPA9_2->setMaximumSize(QSize(150, 20));
        txt_NPA10 = new QLabel(ACM);
        txt_NPA10->setObjectName(QStringLiteral("txt_NPA10"));
        txt_NPA10->setGeometry(QRect(530, 530, 150, 20));
        txt_NPA10->setMinimumSize(QSize(150, 20));
        txt_NPA10->setMaximumSize(QSize(150, 20));
        txt_NPA10_2 = new QLabel(ACM);
        txt_NPA10_2->setObjectName(QStringLiteral("txt_NPA10_2"));
        txt_NPA10_2->setGeometry(QRect(760, 530, 150, 20));
        txt_NPA10_2->setMinimumSize(QSize(150, 20));
        txt_NPA10_2->setMaximumSize(QSize(150, 20));
        txt_NPA11 = new QLabel(ACM);
        txt_NPA11->setObjectName(QStringLiteral("txt_NPA11"));
        txt_NPA11->setGeometry(QRect(530, 560, 150, 20));
        txt_NPA11->setMinimumSize(QSize(150, 20));
        txt_NPA11->setMaximumSize(QSize(150, 20));
        txt_NPA11_2 = new QLabel(ACM);
        txt_NPA11_2->setObjectName(QStringLiteral("txt_NPA11_2"));
        txt_NPA11_2->setGeometry(QRect(760, 560, 150, 20));
        txt_NPA11_2->setMinimumSize(QSize(150, 20));
        txt_NPA11_2->setMaximumSize(QSize(150, 20));
        txt_NPA12 = new QLabel(ACM);
        txt_NPA12->setObjectName(QStringLiteral("txt_NPA12"));
        txt_NPA12->setGeometry(QRect(530, 590, 150, 20));
        txt_NPA12->setMinimumSize(QSize(150, 20));
        txt_NPA12->setMaximumSize(QSize(150, 20));
        txt_NPA12_2 = new QLabel(ACM);
        txt_NPA12_2->setObjectName(QStringLiteral("txt_NPA12_2"));
        txt_NPA12_2->setGeometry(QRect(760, 590, 150, 20));
        txt_NPA12_2->setMinimumSize(QSize(150, 20));
        txt_NPA12_2->setMaximumSize(QSize(150, 20));
        backButton = new QPushButton(ACM);
        backButton->setObjectName(QStringLiteral("backButton"));
        backButton->setGeometry(QRect(660, 0, 83, 25));
        ACMTitle = new QLabel(ACM);
        ACMTitle->setObjectName(QStringLiteral("ACMTitle"));
        ACMTitle->setGeometry(QRect(170, 10, 131, 31));
        ACMTitle->setFont(font);
        ACMTitle->setLayoutDirection(Qt::LeftToRight);
        ACMResultsTable = new QTableWidget(ACM);
        if (ACMResultsTable->columnCount() < 3)
            ACMResultsTable->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        ACMResultsTable->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        ACMResultsTable->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        ACMResultsTable->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        ACMResultsTable->setObjectName(QStringLiteral("ACMResultsTable"));
        ACMResultsTable->setGeometry(QRect(30, 50, 421, 551));
        ACMResultsTable->setEditTriggers(QAbstractItemView::NoEditTriggers);
        ACMResultsTable->horizontalHeader()->setDefaultSectionSize(130);
        ACMResultsTable->horizontalHeader()->setMinimumSectionSize(30);
        ACMResultsTable->verticalHeader()->setMinimumSectionSize(30);

        retranslateUi(ACM);

        QMetaObject::connectSlotsByName(ACM);
    } // setupUi

    void retranslateUi(QDialog *ACM)
    {
        ACM->setWindowTitle(QApplication::translate("ACM", "Dialog", Q_NULLPTR));
        label->setText(QApplication::translate("ACM", "Client", Q_NULLPTR));
        label_2->setText(QApplication::translate("ACM", "Animal", Q_NULLPTR));
        cname_label->setText(QApplication::translate("ACM", "Name", Q_NULLPTR));
        aname_label->setText(QApplication::translate("ACM", "Name", Q_NULLPTR));
        txt_clientname->setText(QString());
        txt_animalname->setText(QString());
        PAtitle_label->setText(QApplication::translate("ACM", "Physical Attributes", Q_NULLPTR));
        cspecies_label->setText(QApplication::translate("ACM", "Species", Q_NULLPTR));
        aspecies_label->setText(QApplication::translate("ACM", "Species", Q_NULLPTR));
        txt_cspecies->setText(QString());
        txt_aspecies->setText(QString());
        cbreed_label->setText(QApplication::translate("ACM", "Breed", Q_NULLPTR));
        abreed_label->setText(QApplication::translate("ACM", "Breed", Q_NULLPTR));
        csex_label->setText(QApplication::translate("ACM", "Sex", Q_NULLPTR));
        asex_label->setText(QApplication::translate("ACM", "Sex", Q_NULLPTR));
        txt_cbreed->setText(QString());
        txt_abreed->setText(QString());
        txt_csex->setText(QString());
        txt_asex->setText(QString());
        cage_label->setText(QApplication::translate("ACM", "Age", Q_NULLPTR));
        aage_label->setText(QApplication::translate("ACM", "Age", Q_NULLPTR));
        txt_cage->setText(QString());
        txt_aage->setText(QString());
        NPAtitle_label->setText(QApplication::translate("ACM", "Non-Physical Attributes", Q_NULLPTR));
        NPA1_label->setText(QApplication::translate("ACM", "NPA1", Q_NULLPTR));
        NPA1_label_2->setText(QApplication::translate("ACM", "NPA1", Q_NULLPTR));
        txt_NPA1->setText(QString());
        txt_NPA1_2->setText(QString());
        NPA2_label->setText(QApplication::translate("ACM", "NPA2", Q_NULLPTR));
        NPA2_label_2->setText(QApplication::translate("ACM", "NPA2", Q_NULLPTR));
        NPA3_label->setText(QApplication::translate("ACM", "NPA3", Q_NULLPTR));
        NPA3_label_2->setText(QApplication::translate("ACM", "NPA3", Q_NULLPTR));
        NPA4_label->setText(QApplication::translate("ACM", "NPA4", Q_NULLPTR));
        NPA4_label_2->setText(QApplication::translate("ACM", "NPA4", Q_NULLPTR));
        NPA5_label->setText(QApplication::translate("ACM", "NPA5", Q_NULLPTR));
        NPA5_label_2->setText(QApplication::translate("ACM", "NPA5", Q_NULLPTR));
        NPA6_label->setText(QApplication::translate("ACM", "NPA6", Q_NULLPTR));
        NPA6_label_2->setText(QApplication::translate("ACM", "NPA6", Q_NULLPTR));
        NPA7_label->setText(QApplication::translate("ACM", "NPA7", Q_NULLPTR));
        NPA7_label_2->setText(QApplication::translate("ACM", "NPA7", Q_NULLPTR));
        NPA8_label->setText(QApplication::translate("ACM", "NPA8", Q_NULLPTR));
        NPA8_label_2->setText(QApplication::translate("ACM", "NPA8", Q_NULLPTR));
        NPA9_label->setText(QApplication::translate("ACM", "NPA9", Q_NULLPTR));
        NPA9_label_2->setText(QApplication::translate("ACM", "NPA9", Q_NULLPTR));
        NPA10_label->setText(QApplication::translate("ACM", "NPA10", Q_NULLPTR));
        NPA10_label_2->setText(QApplication::translate("ACM", "NPA10", Q_NULLPTR));
        NPA11_label->setText(QApplication::translate("ACM", "NPA11", Q_NULLPTR));
        NPA11_label_2->setText(QApplication::translate("ACM", "NPA11", Q_NULLPTR));
        NPA12_label->setText(QApplication::translate("ACM", "NPA12", Q_NULLPTR));
        NPA12_label_2->setText(QApplication::translate("ACM", "NPA12", Q_NULLPTR));
        txt_NPA2->setText(QString());
        txt_NPA2_2->setText(QString());
        txt_NPA3->setText(QString());
        txt_NPA3_2->setText(QString());
        txt_NPA4->setText(QString());
        txt_NPA4_2->setText(QString());
        txt_NPA5->setText(QString());
        txt_NPA5_2->setText(QString());
        txt_NPA6->setText(QString());
        txt_NPA6_2->setText(QString());
        txt_NPA7->setText(QString());
        txt_NPA7_2->setText(QString());
        txt_NPA8->setText(QString());
        txt_NPA8_2->setText(QString());
        txt_NPA9->setText(QString());
        txt_NPA9_2->setText(QString());
        txt_NPA10->setText(QString());
        txt_NPA10_2->setText(QString());
        txt_NPA11->setText(QString());
        txt_NPA11_2->setText(QString());
        txt_NPA12->setText(QString());
        txt_NPA12_2->setText(QString());
        backButton->setText(QApplication::translate("ACM", "Back", Q_NULLPTR));
        ACMTitle->setText(QApplication::translate("ACM", "ACM Results", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem = ACMResultsTable->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("ACM", "Client", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem1 = ACMResultsTable->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("ACM", "Animal", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem2 = ACMResultsTable->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("ACM", "Match Score", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class ACM: public Ui_ACM {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ACM_H
